<a href="https://colab.research.google.com/github/PriyaAnbalagan2027/Data-science-/blob/main/Copy_of_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:

text = "Hi there sam!"
split_string = text.split()
print(split_string)

['Hi', 'there', 'sam!']


## 2. Use .format() to print the following string.

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:

planet = "Earth"
diameter = 12742

output_string = "The diameter of {} is {} kilometers.".format(planet, diameter)
print(output_string)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:

word =d['k1'][3]['tricky'][3]['target'][3]
print(word)

TypeError: ignored

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros?
## 4.2 Create an array of 10 fives?

In [ ]:

import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:

import numpy as np

fives_array = np.full(10, 5)
print(fives_array)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:

import numpy as np

even_array = np.arange(20, 36, 2)
print(even_array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:

import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenated_array = np.concatenate((a, b))
print(concatenated_array)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:

import pandas as pd

data = {'Column1': [1, 2, 3],
        'Column2': ['A', 'B', 'C']}

df = pd.DataFrame(data)
print(df)

   Column1 Column2
0        1       A
1        2       B
2        3       C


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:

import pandas as pd

date_range = pd.date_range(start='2023-01-01', end='2023-02-10')
print(date_range)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:

import pandas as pd

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame(lists, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1 Column2  Column3
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24
