<a href="https://colab.research.google.com/github/PriyaAnbalagan2027/Data-science-/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np1=np.array([10,20,5,7])
print(np1)

[10 20  5  7]


In [ ]:
import numpy as np
np1=np.zeros([1,2])
print(np1)

[[0. 0.]]


In [ ]:
np1=np.ones([1,6])
print(np1)

[[1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
np1=np.arange(20)
print(np1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
np1=np.linspace(1,8,3)
print(np1)

[1.  4.5 8. ]


In [ ]:
import numpy as np
np1=np.eye(3,3)
print(np1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np1=np.array([1,2,4,5])
print(np1.shape)

(4,)


In [ ]:
import numpy as np

arr= np.array([1, 2, 3, 4])
print(arr.ndim)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

1
2


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

6


In [ ]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print(arr.dtype)

float64


In [ ]:
import numpy as np

arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
Add= np.add(arr1, arr2)
print(Add)

[5 7 9]


In [ ]:
arr1=np.array([4,6,7])
arr2=np.array([1,2,4])
Subtract=np.subtract(arr1,arr2)
print(Subtract)

[3 4 3]


In [ ]:
arr1=np.array([2,4])
arr2=np.array([1,5])
Multiply=np.multiply(arr1,arr2)
print(Multiply)

[ 2 20]


In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

dot_product = np.dot(array1, array2)
print(dot_product)

32


In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape((3, 2))
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((array1, array2))
print(concatenated_array)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(array, 3)
print(split_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])

transposed_array = array.T

print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
sum_result = np.sum(my_array)
print("Sum:", sum_result)
mean_result = np.mean(my_array)
print("Mean:", mean_result)
median_result = np.median(my_array)
print("Median:", median_result)
std_result = np.std(my_array)
print("Standard Deviation:", std_result)
min_result = np.min(my_array)
print("Minimum:", min_result)
max_result = np.max(my_array)
print("Maximum:", max_result)

Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Minimum: 1
Maximum: 5


In [ ]:
import numpy as np
angle = np.pi / 4
sin_value = np.sin(angle)
cos_value = np.cos(angle)
tan_value = np.tan(angle)
print(f'Sine: {sin_value}')
print(f'Cosine: {cos_value}')
print(f'Tangent: {tan_value}')

Sine: 0.7071067811865475
Cosine: 0.7071067811865476
Tangent: 0.9999999999999999


In [ ]:
import numpy as np
value = 0.7071
arcsin_result = np.arcsin(value)
arccos_result = np.arccos(value)
arctan_result = np.arctan(value)
arcsin_degrees = np.degrees(arcsin_result)
arccos_degrees = np.degrees(arccos_result)
arctan_degrees = np.degrees(arctan_result)
print(f'Arcsin: {arcsin_result} radians or {arcsin_degrees} degrees')
print(f'Arccos: {arccos_result} radians or {arccos_degrees} degrees')
print(f'Arctan: {arctan_result} radians or {arctan_degrees} degrees')

Arcsin: 0.7853885733974476 radians or 44.99945053347443 degrees
Arccos: 0.785407753397449 radians or 45.00054946652557 degrees
Arctan: 0.6154751878649041 radians or 35.26413065968046 degrees


In [ ]:
import numpy as np
random_float = np.random.random()
random_integer = np.random.randint(1, 10)
random_array = np.random.random((3, 3))
print(f'Random Float: {random_float}')
print(f'Random Integer: {random_integer}')
print(f'Random Array:\n{random_array}')

Random Float: 0.8076921382879966
Random Integer: 3
Random Array:
[[0.45003349 0.41258678 0.00532783]
 [0.5188565  0.15715972 0.41324328]
 [0.36259107 0.00873107 0.94396279]]


In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(my_array)
print(my_array)

[2 4 3 1 5]


In [ ]:
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentile_25 = np.percentile(data, 25)
print(f'25th Percentile: {percentile_25}')

25th Percentile: 3.25


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
correlation_coefficient = np.corrcoef(x, y)[0,1]

print(f"Correlation Coefficient: {correlation_coefficient}")

Correlation Coefficient: -0.9999999999999999


In [ ]:
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

result_and = np.logical_and(arr1, arr2)

print(result_and)

[ True False False False]


In [ ]:
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

result_or = np.logical_or(arr1, arr2)

print(result_or)

[ True  True  True False]


In [ ]:
import numpy as np

arr = np.array([True, False, True, False])

result_not = np.logical_not(arr)

print(result_not)

[False  True False  True]


In [ ]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)
desc_sorted_arr = np.sort(arr)[::-1]
print(desc_sorted_arr)

[1 1 2 3 3 4 5 5 5 6 9]
[9 6 5 5 5 4 3 3 2 1 1]
